name: Echo Cron
on:
schedule:
- cron: "*/5 * * * *"
jobs:
ping:
runs-on: ubuntu-latest
steps:
- run: |
curl -sS -X POST "$CRON_URL" -H "x-cron-secret: $CRON_SECRET"
env:
CRON_URL: ${{ secrets.CRON_URL }}
CRON_SECRET: ${{ secrets.CRON_SECRET }}
